"""add engineering evidence

Milestone 28.1: the three tables holding deterministic engineering
evidence - set, evidence item, and the canonical spans each item drew
characters from.

**Purely additive.** Three new tables and their indexes; no existing
table, column or constraint is touched. The canonical text tables in
particular are untouched: evidence is derived *from* canonical text, and
deriving something must never modify what it was derived from.

``engineering_evidence.quantity_value`` is ``Numeric``, never ``Float``.
A rated voltage that read back as 20.000000000000004 kV would be a defect
nobody could explain to an engineer.

The natural-key constraint on (document_id, content_checksum,
extraction_policy_version) is the persistence-level idempotency backstop:
re-extracting the same canonical source under the same policy cannot
produce a second row, while a changed document or a changed rule
catalogue produces a new set alongside - never over - the old one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d9fadeeb4c'
down_revision: Union[str, Sequence[str], None] = '26978efc7d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_evidence_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('content_checksum', sa.String(length=128), nullable=False),
    sa.Column('segmentation_version', sa.String(length=20), nullable=False),
    sa.Column('extraction_policy_version', sa.String(length=20), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_checksum', 'extraction_policy_version', name='uq_engineering_evidence_set_source_policy')
    )
    op.create_index(op.f('ix_engineering_evidence_sets_content_checksum'), 'engineering_evidence_sets', ['content_checksum'], unique=False)
    op.create_index('ix_engineering_evidence_sets_document_created', 'engineering_evidence_sets', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_engineering_evidence_sets_document_id'), 'engineering_evidence_sets', ['document_id'], unique=False)
    op.create_index(op.f('ix_engineering_evidence_sets_id'), 'engineering_evidence_sets', ['id'], unique=False)
    op.create_index(op.f('ix_engineering_evidence_sets_project_id'), 'engineering_evidence_sets', ['project_id'], unique=False)
    op.create_table('engineering_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_set_id', sa.Integer(), nullable=False),
    sa.Column('evidence_key', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.Enum('DESIGNATION', 'VOLTAGE_VALUE', 'CURRENT_VALUE', 'POWER_VALUE', 'CABLE_SECTION_VALUE', name='evidencetype'), nullable=False),
    sa.Column('status', sa.Enum('OBSERVED', 'AMBIGUOUS', 'REJECTED', name='evidencestatus'), nullable=False),
    sa.Column('observed_text', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.String(length=60), nullable=False),
    sa.Column('rule_version', sa.String(length=20), nullable=False),
    sa.Column('quantity_value', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('quantity_unit', sa.String(length=10), nullable=True),
    sa.Column('quantity_base_value', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('quantity_base_unit', sa.String(length=10), nullable=True),
    sa.Column('designation_normalized', sa.String(length=60), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('block_reading_order', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('token_start', sa.Integer(), nullable=False),
    sa.Column('token_end', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_set_id'], ['engineering_evidence_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_set_id', 'evidence_key', name='uq_engineering_evidence_key')
    )
    op.create_index('ix_engineering_evidence_designation', 'engineering_evidence', ['designation_normalized'], unique=False)
    op.create_index(op.f('ix_engineering_evidence_evidence_key'), 'engineering_evidence', ['evidence_key'], unique=False)
    op.create_index(op.f('ix_engineering_evidence_evidence_set_id'), 'engineering_evidence', ['evidence_set_id'], unique=False)
    op.create_index(op.f('ix_engineering_evidence_id'), 'engineering_evidence', ['id'], unique=False)
    op.create_index('ix_engineering_evidence_type_status', 'engineering_evidence', ['evidence_type', 'status'], unique=False)
    op.create_table('engineering_evidence_spans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('span_reading_order', sa.Integer(), nullable=False),
    sa.Column('character_start', sa.Integer(), nullable=False),
    sa.Column('character_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['engineering_evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineering_evidence_spans_evidence_id'), 'engineering_evidence_spans', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_engineering_evidence_spans_id'), 'engineering_evidence_spans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engineering_evidence_spans_id'), table_name='engineering_evidence_spans')
    op.drop_index(op.f('ix_engineering_evidence_spans_evidence_id'), table_name='engineering_evidence_spans')
    op.drop_table('engineering_evidence_spans')
    op.drop_index('ix_engineering_evidence_type_status', table_name='engineering_evidence')
    op.drop_index(op.f('ix_engineering_evidence_id'), table_name='engineering_evidence')
    op.drop_index(op.f('ix_engineering_evidence_evidence_set_id'), table_name='engineering_evidence')
    op.drop_index(op.f('ix_engineering_evidence_evidence_key'), table_name='engineering_evidence')
    op.drop_index('ix_engineering_evidence_designation', table_name='engineering_evidence')
    op.drop_table('engineering_evidence')
    op.drop_index(op.f('ix_engineering_evidence_sets_project_id'), table_name='engineering_evidence_sets')
    op.drop_index(op.f('ix_engineering_evidence_sets_id'), table_name='engineering_evidence_sets')
    op.drop_index(op.f('ix_engineering_evidence_sets_document_id'), table_name='engineering_evidence_sets')
    op.drop_index('ix_engineering_evidence_sets_document_created', table_name='engineering_evidence_sets')
    op.drop_index(op.f('ix_engineering_evidence_sets_content_checksum'), table_name='engineering_evidence_sets')
    op.drop_table('engineering_evidence_sets')
    # ### end Alembic commands ###
