"""add canonical text segmentation

Milestone 27.1: the five tables holding the canonical text segmentation -
document, section, paragraph, line, token.

**Purely additive.** Five new tables and their indexes; no existing
table, column or constraint is touched. In particular the canonical
representation's own tables are untouched: a segmentation is derived
*from* a representation, and deriving something must never modify what it
was derived from.

The natural-key uniqueness constraint on (document_id, content_checksum,
segmentation_version) is the persistence-level idempotency backstop:
re-segmenting the same representation under the same rules cannot produce
a second row whatever the caller does, while a new checksum (the document
changed) or a new segmentation version (the rules changed) is a new row
alongside - never over - the old one.

``canonical_text_tokens`` carries the provenance chain
(page → block → span → character range) as columns rather than as joins,
because "find this term and tell me exactly where it sits" is the read
every future extractor performs, and it must not cost four joins.

Revision ID: 26978efc7d15
Revises: b7ded1e07fcd
Create Date: 2026-07-28

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26978efc7d15'
down_revision: Union[str, Sequence[str], None] = 'b7ded1e07fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_text_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('content_checksum', sa.String(length=128), nullable=False),
    sa.Column('representation_version', sa.String(length=20), nullable=False),
    sa.Column('segmentation_version', sa.String(length=20), nullable=False),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_checksum', 'segmentation_version', name='uq_canonical_text_document_checksum_version')
    )
    op.create_index(op.f('ix_canonical_text_documents_content_checksum'), 'canonical_text_documents', ['content_checksum'], unique=False)
    op.create_index('ix_canonical_text_documents_document_created', 'canonical_text_documents', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_canonical_text_documents_document_id'), 'canonical_text_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_canonical_text_documents_id'), 'canonical_text_documents', ['id'], unique=False)
    op.create_table('canonical_text_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_document_id', sa.Integer(), nullable=False),
    sa.Column('section_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_document_id'], ['canonical_text_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_document_id', 'section_index', name='uq_canonical_text_section_index')
    )
    op.create_index(op.f('ix_canonical_text_sections_id'), 'canonical_text_sections', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_text_sections_text_document_id'), 'canonical_text_sections', ['text_document_id'], unique=False)
    op.create_table('canonical_text_paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('block_reading_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['canonical_text_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'paragraph_index', name='uq_canonical_text_paragraph_index')
    )
    op.create_index(op.f('ix_canonical_text_paragraphs_id'), 'canonical_text_paragraphs', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_text_paragraphs_section_id'), 'canonical_text_paragraphs', ['section_id'], unique=False)
    op.create_table('canonical_text_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paragraph_id'], ['canonical_text_paragraphs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_text_lines_id'), 'canonical_text_lines', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_text_lines_paragraph_id'), 'canonical_text_lines', ['paragraph_id'], unique=False)
    op.create_table('canonical_text_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('block_reading_order', sa.Integer(), nullable=False),
    sa.Column('span_reading_order', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('character_start', sa.Integer(), nullable=False),
    sa.Column('character_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['canonical_text_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('line_id', 'position', name='uq_canonical_text_token_position')
    )
    op.create_index(op.f('ix_canonical_text_tokens_id'), 'canonical_text_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_text_tokens_line_id'), 'canonical_text_tokens', ['line_id'], unique=False)
    op.create_index('ix_canonical_text_tokens_normalized', 'canonical_text_tokens', ['normalized_text'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_canonical_text_tokens_normalized', table_name='canonical_text_tokens')
    op.drop_index(op.f('ix_canonical_text_tokens_line_id'), table_name='canonical_text_tokens')
    op.drop_index(op.f('ix_canonical_text_tokens_id'), table_name='canonical_text_tokens')
    op.drop_table('canonical_text_tokens')
    op.drop_index(op.f('ix_canonical_text_lines_paragraph_id'), table_name='canonical_text_lines')
    op.drop_index(op.f('ix_canonical_text_lines_id'), table_name='canonical_text_lines')
    op.drop_table('canonical_text_lines')
    op.drop_index(op.f('ix_canonical_text_paragraphs_section_id'), table_name='canonical_text_paragraphs')
    op.drop_index(op.f('ix_canonical_text_paragraphs_id'), table_name='canonical_text_paragraphs')
    op.drop_table('canonical_text_paragraphs')
    op.drop_index(op.f('ix_canonical_text_sections_text_document_id'), table_name='canonical_text_sections')
    op.drop_index(op.f('ix_canonical_text_sections_id'), table_name='canonical_text_sections')
    op.drop_table('canonical_text_sections')
    op.drop_index(op.f('ix_canonical_text_documents_id'), table_name='canonical_text_documents')
    op.drop_index(op.f('ix_canonical_text_documents_document_id'), table_name='canonical_text_documents')
    op.drop_index('ix_canonical_text_documents_document_created', table_name='canonical_text_documents')
    op.drop_index(op.f('ix_canonical_text_documents_content_checksum'), table_name='canonical_text_documents')
    op.drop_table('canonical_text_documents')
    # ### end Alembic commands ###
