"""add engineering entities

Milestone 29.1: the three tables holding deterministic entity
resolution - entity set, entity, and the evidence each entity was
resolved from.

**Purely additive.** Three new tables and their indexes; no existing
table, column or constraint is touched. The engineering evidence tables
in particular are untouched: entities are resolved *from* evidence, and
resolving something must never modify what it was resolved from. Nothing
here writes to the Knowledge Graph.

``engineering_entities.quantity_value`` is ``Numeric``, never ``Float``,
for the same reason it is on the evidence table: a rated value that read
back as 20.000000000000004 kV would be a defect nobody could explain.

The natural-key constraint on (document_id, content_checksum,
resolution_policy_version) is the persistence-level idempotency backstop:
re-resolving the same evidence under the same rules cannot produce a
second row, while new evidence or a new rule catalogue produces a new set
alongside - never over - the old one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ec4e0fe42f'
down_revision: Union[str, Sequence[str], None] = '58327939f9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_entity_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('content_checksum', sa.String(length=128), nullable=False),
    sa.Column('extraction_policy_version', sa.String(length=20), nullable=False),
    sa.Column('resolution_policy_version', sa.String(length=20), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_checksum', 'resolution_policy_version', name='uq_engineering_entity_set_source_policy')
    )
    op.create_index(op.f('ix_engineering_entity_sets_content_checksum'), 'engineering_entity_sets', ['content_checksum'], unique=False)
    op.create_index('ix_engineering_entity_sets_document_created', 'engineering_entity_sets', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_engineering_entity_sets_document_id'), 'engineering_entity_sets', ['document_id'], unique=False)
    op.create_index(op.f('ix_engineering_entity_sets_id'), 'engineering_entity_sets', ['id'], unique=False)
    op.create_index(op.f('ix_engineering_entity_sets_project_id'), 'engineering_entity_sets', ['project_id'], unique=False)
    op.create_table('engineering_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_set_id', sa.Integer(), nullable=False),
    sa.Column('entity_key', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.Enum('EQUIPMENT_DESIGNATION', 'ENGINEERING_QUANTITY', name='entitytype'), nullable=False),
    sa.Column('status', sa.Enum('RESOLVED', 'AMBIGUOUS', name='entitystatus'), nullable=False),
    sa.Column('entity_version', sa.String(length=20), nullable=False),
    sa.Column('resolution_rule_id', sa.String(length=60), nullable=False),
    sa.Column('resolution_rule_version', sa.String(length=20), nullable=False),
    sa.Column('designation_normalized', sa.String(length=60), nullable=True),
    sa.Column('quantity_value', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('quantity_unit', sa.String(length=10), nullable=True),
    sa.Column('quantity_base_value', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('quantity_base_unit', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['entity_set_id'], ['engineering_entity_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_set_id', 'entity_key', name='uq_engineering_entity_key')
    )
    op.create_index('ix_engineering_entities_designation', 'engineering_entities', ['designation_normalized'], unique=False)
    op.create_index(op.f('ix_engineering_entities_entity_key'), 'engineering_entities', ['entity_key'], unique=False)
    op.create_index(op.f('ix_engineering_entities_entity_set_id'), 'engineering_entities', ['entity_set_id'], unique=False)
    op.create_index(op.f('ix_engineering_entities_id'), 'engineering_entities', ['id'], unique=False)
    op.create_index('ix_engineering_entities_type_status', 'engineering_entities', ['entity_type', 'status'], unique=False)
    op.create_table('engineering_entity_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('evidence_key', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.Enum('DESIGNATION', 'VOLTAGE_VALUE', 'CURRENT_VALUE', 'POWER_VALUE', 'CABLE_SECTION_VALUE', name='evidencetype'), nullable=False),
    sa.Column('observed_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('token_start', sa.Integer(), nullable=False),
    sa.Column('token_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['engineering_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'evidence_key', name='uq_engineering_entity_evidence_key')
    )
    op.create_index(op.f('ix_engineering_entity_evidence_entity_id'), 'engineering_entity_evidence', ['entity_id'], unique=False)
    op.create_index(op.f('ix_engineering_entity_evidence_id'), 'engineering_entity_evidence', ['id'], unique=False)
    op.create_index('ix_engineering_entity_evidence_key', 'engineering_entity_evidence', ['evidence_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_engineering_entity_evidence_key', table_name='engineering_entity_evidence')
    op.drop_index(op.f('ix_engineering_entity_evidence_id'), table_name='engineering_entity_evidence')
    op.drop_index(op.f('ix_engineering_entity_evidence_entity_id'), table_name='engineering_entity_evidence')
    op.drop_table('engineering_entity_evidence')
    op.drop_index('ix_engineering_entities_type_status', table_name='engineering_entities')
    op.drop_index(op.f('ix_engineering_entities_id'), table_name='engineering_entities')
    op.drop_index(op.f('ix_engineering_entities_entity_set_id'), table_name='engineering_entities')
    op.drop_index(op.f('ix_engineering_entities_entity_key'), table_name='engineering_entities')
    op.drop_index('ix_engineering_entities_designation', table_name='engineering_entities')
    op.drop_table('engineering_entities')
    op.drop_index(op.f('ix_engineering_entity_sets_project_id'), table_name='engineering_entity_sets')
    op.drop_index(op.f('ix_engineering_entity_sets_id'), table_name='engineering_entity_sets')
    op.drop_index(op.f('ix_engineering_entity_sets_document_id'), table_name='engineering_entity_sets')
    op.drop_index('ix_engineering_entity_sets_document_created', table_name='engineering_entity_sets')
    op.drop_index(op.f('ix_engineering_entity_sets_content_checksum'), table_name='engineering_entity_sets')
    op.drop_table('engineering_entity_sets')
    # ### end Alembic commands ###
