"""add engineering semantics

Milestone 30.1: the four tables holding interpreted engineering meaning -
semantic set, statement, the facts supporting each statement, and the
interpretation diagnostics.

**Purely additive.** Four new tables and their indexes; no existing
table, column or constraint is touched. The fact, entity and evidence
tables in particular are untouched: statements are interpreted *from*
facts, and interpreting something must never modify what it was
interpreted from. Nothing here writes to the Knowledge Graph.

``engineering_semantic_statements`` references entities and facts by
their **deterministic keys, not by foreign key**, for the same reason
facts reference entities that way: a re-resolution or re-construction
upstream produces new sets, and a foreign key would either block that or
cascade a historical interpretation into nothing.

There is deliberately **no value or unit column** on a statement. The
figure lives on the quantity entity; a copy here would be a second source
of truth for a rated value.

``engineering_semantic_diagnostics`` is a separate table rather than
statements with a softer status, so an undecided meaning is structurally
invisible to anyone querying interpreted knowledge.

The natural-key constraint on (document_id, content_checksum,
resolution_policy_version, fact_policy_version, semantic_policy_version)
is the persistence-level idempotency backstop: re-running over the same
fact source under the same rules cannot produce a second row, while new
facts or a new rule catalogue produce a new set alongside - never over -
the old one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7300ff6a7531'
down_revision: Union[str, Sequence[str], None] = '86c866388a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_semantic_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('content_checksum', sa.String(length=128), nullable=False),
    sa.Column('resolution_policy_version', sa.String(length=20), nullable=False),
    sa.Column('fact_policy_version', sa.String(length=20), nullable=False),
    sa.Column('semantic_policy_version', sa.String(length=20), nullable=False),
    sa.Column('statement_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_checksum', 'resolution_policy_version', 'fact_policy_version', 'semantic_policy_version', name='uq_engineering_semantic_set_source_policy')
    )
    op.create_index(op.f('ix_engineering_semantic_sets_content_checksum'), 'engineering_semantic_sets', ['content_checksum'], unique=False)
    op.create_index('ix_engineering_semantic_sets_document_created', 'engineering_semantic_sets', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_engineering_semantic_sets_document_id'), 'engineering_semantic_sets', ['document_id'], unique=False)
    op.create_index(op.f('ix_engineering_semantic_sets_id'), 'engineering_semantic_sets', ['id'], unique=False)
    op.create_index(op.f('ix_engineering_semantic_sets_project_id'), 'engineering_semantic_sets', ['project_id'], unique=False)
    op.create_table('engineering_semantic_diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semantic_set_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('MULTIPLE_CANDIDATE_QUANTITIES', name='semanticambiguityreason'), nullable=False),
    sa.Column('subject_entity_key', sa.String(length=64), nullable=False),
    sa.Column('candidate_fact_keys', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['semantic_set_id'], ['engineering_semantic_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineering_semantic_diagnostics_id'), 'engineering_semantic_diagnostics', ['id'], unique=False)
    op.create_index(op.f('ix_engineering_semantic_diagnostics_semantic_set_id'), 'engineering_semantic_diagnostics', ['semantic_set_id'], unique=False)
    op.create_table('engineering_semantic_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semantic_set_id', sa.Integer(), nullable=False),
    sa.Column('statement_key', sa.String(length=64), nullable=False),
    sa.Column('statement_type', sa.Enum('HAS_RATED_POWER', name='semanticstatementtype'), nullable=False),
    sa.Column('subject_entity_key', sa.String(length=64), nullable=False),
    sa.Column('object_entity_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('INTERPRETED', 'AMBIGUOUS', name='semanticstatementstatus'), nullable=False),
    sa.Column('semantic_contract_version', sa.String(length=20), nullable=False),
    sa.Column('semantic_rule_id', sa.String(length=80), nullable=False),
    sa.Column('semantic_rule_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['semantic_set_id'], ['engineering_semantic_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semantic_set_id', 'statement_key', name='uq_engineering_semantic_statement_key')
    )
    op.create_index(op.f('ix_engineering_semantic_statements_id'), 'engineering_semantic_statements', ['id'], unique=False)
    op.create_index(op.f('ix_engineering_semantic_statements_semantic_set_id'), 'engineering_semantic_statements', ['semantic_set_id'], unique=False)
    op.create_index(op.f('ix_engineering_semantic_statements_statement_key'), 'engineering_semantic_statements', ['statement_key'], unique=False)
    op.create_index('ix_engineering_semantic_statements_subject', 'engineering_semantic_statements', ['subject_entity_key'], unique=False)
    op.create_index('ix_engineering_semantic_statements_type_status', 'engineering_semantic_statements', ['statement_type', 'status'], unique=False)
    op.create_table('engineering_semantic_statement_support',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('fact_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['engineering_semantic_statements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statement_id', 'fact_key', name='uq_engineering_semantic_support')
    )
    op.create_index(op.f('ix_engineering_semantic_statement_support_id'), 'engineering_semantic_statement_support', ['id'], unique=False)
    op.create_index(op.f('ix_engineering_semantic_statement_support_statement_id'), 'engineering_semantic_statement_support', ['statement_id'], unique=False)
    op.create_index('ix_engineering_semantic_support_fact', 'engineering_semantic_statement_support', ['fact_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_engineering_semantic_support_fact', table_name='engineering_semantic_statement_support')
    op.drop_index(op.f('ix_engineering_semantic_statement_support_statement_id'), table_name='engineering_semantic_statement_support')
    op.drop_index(op.f('ix_engineering_semantic_statement_support_id'), table_name='engineering_semantic_statement_support')
    op.drop_table('engineering_semantic_statement_support')
    op.drop_index('ix_engineering_semantic_statements_type_status', table_name='engineering_semantic_statements')
    op.drop_index('ix_engineering_semantic_statements_subject', table_name='engineering_semantic_statements')
    op.drop_index(op.f('ix_engineering_semantic_statements_statement_key'), table_name='engineering_semantic_statements')
    op.drop_index(op.f('ix_engineering_semantic_statements_semantic_set_id'), table_name='engineering_semantic_statements')
    op.drop_index(op.f('ix_engineering_semantic_statements_id'), table_name='engineering_semantic_statements')
    op.drop_table('engineering_semantic_statements')
    op.drop_index(op.f('ix_engineering_semantic_diagnostics_semantic_set_id'), table_name='engineering_semantic_diagnostics')
    op.drop_index(op.f('ix_engineering_semantic_diagnostics_id'), table_name='engineering_semantic_diagnostics')
    op.drop_table('engineering_semantic_diagnostics')
    op.drop_index(op.f('ix_engineering_semantic_sets_project_id'), table_name='engineering_semantic_sets')
    op.drop_index(op.f('ix_engineering_semantic_sets_id'), table_name='engineering_semantic_sets')
    op.drop_index(op.f('ix_engineering_semantic_sets_document_id'), table_name='engineering_semantic_sets')
    op.drop_index('ix_engineering_semantic_sets_document_created', table_name='engineering_semantic_sets')
    op.drop_index(op.f('ix_engineering_semantic_sets_content_checksum'), table_name='engineering_semantic_sets')
    op.drop_table('engineering_semantic_sets')
    # ### end Alembic commands ###
