"""add engineering facts

Milestone 29.2: the four tables holding deterministic fact construction -
fact set, fact, the observations supporting each fact, and the
construction diagnostics.

**Purely additive.** Four new tables and their indexes; no existing
table, column or constraint is touched. The entity and evidence tables in
particular are untouched: facts are constructed *from* entities, and
constructing something must never modify what it was constructed from.
Nothing here writes to the Knowledge Graph.

``engineering_facts.subject_entity_key`` and ``object_entity_key`` are
**plain strings, not foreign keys** into ``engineering_entities``. That
is deliberate: a later re-resolution produces a new entity set, and a
foreign key would either block it or cascade a historical fact set into
nothing. Fact history must survive newer entities, so entities are
referenced by their deterministic key.

``engineering_fact_diagnostics`` is a separate table rather than facts
with a softer status, so that an ambiguous pairing is structurally
invisible to anyone querying ``engineering_facts`` and cannot be read as
a confirmed association.

The natural-key constraint on (document_id, content_checksum,
resolution_policy_version, fact_policy_version) is the
persistence-level idempotency backstop: re-running over the same entity
source under the same rules cannot produce a second row, while new
entities or a new rule catalogue produce a new set alongside - never over
- the old one.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86c866388a33'
down_revision: Union[str, Sequence[str], None] = '46ec4e0fe42f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_fact_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('content_checksum', sa.String(length=128), nullable=False),
    sa.Column('resolution_policy_version', sa.String(length=20), nullable=False),
    sa.Column('fact_policy_version', sa.String(length=20), nullable=False),
    sa.Column('fact_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_checksum', 'resolution_policy_version', 'fact_policy_version', name='uq_engineering_fact_set_source_policy')
    )
    op.create_index(op.f('ix_engineering_fact_sets_content_checksum'), 'engineering_fact_sets', ['content_checksum'], unique=False)
    op.create_index('ix_engineering_fact_sets_document_created', 'engineering_fact_sets', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_engineering_fact_sets_document_id'), 'engineering_fact_sets', ['document_id'], unique=False)
    op.create_index(op.f('ix_engineering_fact_sets_id'), 'engineering_fact_sets', ['id'], unique=False)
    op.create_index(op.f('ix_engineering_fact_sets_project_id'), 'engineering_fact_sets', ['project_id'], unique=False)
    op.create_table('engineering_fact_diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_set_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('MULTIPLE_SUBJECTS', name='ambiguityreason'), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('subject_entity_keys', sa.Text(), nullable=False),
    sa.Column('object_entity_keys', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['fact_set_id'], ['engineering_fact_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineering_fact_diagnostics_fact_set_id'), 'engineering_fact_diagnostics', ['fact_set_id'], unique=False)
    op.create_index(op.f('ix_engineering_fact_diagnostics_id'), 'engineering_fact_diagnostics', ['id'], unique=False)
    op.create_table('engineering_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_set_id', sa.Integer(), nullable=False),
    sa.Column('fact_key', sa.String(length=64), nullable=False),
    sa.Column('subject_entity_key', sa.String(length=64), nullable=False),
    sa.Column('predicate', sa.Enum('HAS_ASSOCIATED_QUANTITY', name='factpredicate'), nullable=False),
    sa.Column('object_entity_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('CONSTRUCTED', 'AMBIGUOUS', name='factstatus'), nullable=False),
    sa.Column('fact_version', sa.String(length=20), nullable=False),
    sa.Column('construction_rule_id', sa.String(length=60), nullable=False),
    sa.Column('construction_rule_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['fact_set_id'], ['engineering_fact_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_set_id', 'fact_key', name='uq_engineering_fact_key')
    )
    op.create_index(op.f('ix_engineering_facts_fact_key'), 'engineering_facts', ['fact_key'], unique=False)
    op.create_index(op.f('ix_engineering_facts_fact_set_id'), 'engineering_facts', ['fact_set_id'], unique=False)
    op.create_index(op.f('ix_engineering_facts_id'), 'engineering_facts', ['id'], unique=False)
    op.create_index('ix_engineering_facts_object', 'engineering_facts', ['object_entity_key'], unique=False)
    op.create_index('ix_engineering_facts_subject', 'engineering_facts', ['subject_entity_key'], unique=False)
    op.create_table('engineering_fact_support',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('evidence_key', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('SUBJECT', 'OBJECT', name='supportrole'), nullable=False),
    sa.Column('evidence_type', sa.Enum('DESIGNATION', 'VOLTAGE_VALUE', 'CURRENT_VALUE', 'POWER_VALUE', 'CABLE_SECTION_VALUE', name='evidencetype'), nullable=False),
    sa.Column('observed_text', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('paragraph_index', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('token_start', sa.Integer(), nullable=False),
    sa.Column('token_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['engineering_facts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_id', 'evidence_key', 'role', name='uq_engineering_fact_support')
    )
    op.create_index('ix_engineering_fact_support_evidence', 'engineering_fact_support', ['evidence_key'], unique=False)
    op.create_index(op.f('ix_engineering_fact_support_fact_id'), 'engineering_fact_support', ['fact_id'], unique=False)
    op.create_index(op.f('ix_engineering_fact_support_id'), 'engineering_fact_support', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engineering_fact_support_id'), table_name='engineering_fact_support')
    op.drop_index(op.f('ix_engineering_fact_support_fact_id'), table_name='engineering_fact_support')
    op.drop_index('ix_engineering_fact_support_evidence', table_name='engineering_fact_support')
    op.drop_table('engineering_fact_support')
    op.drop_index('ix_engineering_facts_subject', table_name='engineering_facts')
    op.drop_index('ix_engineering_facts_object', table_name='engineering_facts')
    op.drop_index(op.f('ix_engineering_facts_id'), table_name='engineering_facts')
    op.drop_index(op.f('ix_engineering_facts_fact_set_id'), table_name='engineering_facts')
    op.drop_index(op.f('ix_engineering_facts_fact_key'), table_name='engineering_facts')
    op.drop_table('engineering_facts')
    op.drop_index(op.f('ix_engineering_fact_diagnostics_id'), table_name='engineering_fact_diagnostics')
    op.drop_index(op.f('ix_engineering_fact_diagnostics_fact_set_id'), table_name='engineering_fact_diagnostics')
    op.drop_table('engineering_fact_diagnostics')
    op.drop_index(op.f('ix_engineering_fact_sets_project_id'), table_name='engineering_fact_sets')
    op.drop_index(op.f('ix_engineering_fact_sets_id'), table_name='engineering_fact_sets')
    op.drop_index(op.f('ix_engineering_fact_sets_document_id'), table_name='engineering_fact_sets')
    op.drop_index('ix_engineering_fact_sets_document_created', table_name='engineering_fact_sets')
    op.drop_index(op.f('ix_engineering_fact_sets_content_checksum'), table_name='engineering_fact_sets')
    op.drop_table('engineering_fact_sets')
    # ### end Alembic commands ###
