"""baseline: all governed tables

Revision ID: b3e2e0f30024
Revises: 
Create Date: 2026-07-24 17:10:05.388804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e2e0f30024'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('customer', sa.String(length=150), nullable=False),
    sa.Column('epc', sa.String(length=150), nullable=True),
    sa.Column('country', sa.String(length=150), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('voltage_level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'ENGINEERING', 'CONSTRUCTION', 'COMMISSIONING', 'ENERGIZED', 'CLOSED', name='projectstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lifecycle_state', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', 'DELETED', name='projectlifecyclestate'), nullable=False),
    sa.Column('canonical_domain_version', sa.String(length=80), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_format', sa.Enum('PDF', 'DWG', 'MODEL_3D', 'XLSX', 'DOCX', 'OTHER', name='documentformat'), nullable=False),
    sa.Column('category', sa.Enum('FUNCTIONAL_SCHEMATIC', 'WIRING_TERMINAL', 'GENERAL_TECHNICAL', 'CABLE_LIST', 'RELAY_SETTINGS', 'COMMISSIONING_REPORT', 'OTHER', name='documentcategory'), nullable=False),
    sa.Column('revision', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=150), nullable=False),
    sa.Column('scope', sa.Enum('PROJECT', 'CANONICAL_LIBRARY', name='documentscope'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_table('graph_operation_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Enum('PROJECT', 'DOCUMENT', name='graphoperationbatchscope'), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_operation_batches_id'), 'graph_operation_batches', ['id'], unique=False)
    op.create_index(op.f('ix_graph_operation_batches_project_id'), 'graph_operation_batches', ['project_id'], unique=False)
    op.create_index(op.f('ix_graph_operation_batches_scope_id'), 'graph_operation_batches', ['scope_id'], unique=False)
    op.create_table('project_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('SUBSTATION', 'BAY', 'PANEL', 'CIRCUIT_BREAKER', 'DISCONNECTOR', 'TRANSFORMER', 'CURRENT_TRANSFORMER', 'VOLTAGE_TRANSFORMER', 'PROTECTION_RELAY', 'CABLE', 'SIGNAL', 'DOCUMENT', 'TEST', 'OTHER', 'BUSBAR', 'LINE', name='entitytype'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_entities_id'), 'project_entities', ['id'], unique=False)
    op.create_index(op.f('ix_project_entities_name'), 'project_entities', ['name'], unique=False)
    op.create_index(op.f('ix_project_entities_project_id'), 'project_entities', ['project_id'], unique=False)
    op.create_table('proposed_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.Enum('RELATIONSHIP', 'ATTRIBUTE', 'EXISTENCE', name='claimtype'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('predicate', sa.String(length=255), nullable=True),
    sa.Column('object', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'claim_type', 'subject', 'predicate', 'object', name='uq_proposed_claim_natural_key')
    )
    op.create_index(op.f('ix_proposed_claims_id'), 'proposed_claims', ['id'], unique=False)
    op.create_index(op.f('ix_proposed_claims_project_id'), 'proposed_claims', ['project_id'], unique=False)
    op.create_index(op.f('ix_proposed_claims_subject'), 'proposed_claims', ['subject'], unique=False)
    op.create_table('engineering_index_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('EQUIPMENT', 'SIGNAL', 'CABLE', 'CABINET_OR_FRAME', 'PROTECTION', 'DRAWING', 'FUNCTION', 'CROSS_REFERENCE', name='engineeringindexentrykind'), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('locator_kind', sa.Enum('PAGE', 'SHEET', 'CELL_RANGE', 'DRAWING_LAYOUT', 'REGION', 'OTHER', name='indexentrylocatorkind'), nullable=False),
    sa.Column('locator_value', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'kind', 'identifier', 'locator_kind', 'locator_value', name='uq_engineering_index_entry_natural_key')
    )
    op.create_index(op.f('ix_engineering_index_entries_document_id'), 'engineering_index_entries', ['document_id'], unique=False)
    op.create_index(op.f('ix_engineering_index_entries_id'), 'engineering_index_entries', ['id'], unique=False)
    op.create_index(op.f('ix_engineering_index_entries_identifier'), 'engineering_index_entries', ['identifier'], unique=False)
    op.create_index(op.f('ix_engineering_index_entries_project_id'), 'engineering_index_entries', ['project_id'], unique=False)
    op.create_table('entity_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('BELONGS_TO', 'CONNECTED_TO', 'PROTECTED_BY', 'DOCUMENTED_IN', 'TESTED_BY', 'PART_OF', 'OTHER', name='relationtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['project_entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['project_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_relations_id'), 'entity_relations', ['id'], unique=False)
    op.create_index(op.f('ix_entity_relations_project_id'), 'entity_relations', ['project_id'], unique=False)
    op.create_index(op.f('ix_entity_relations_source_entity_id'), 'entity_relations', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_relations_target_entity_id'), 'entity_relations', ['target_entity_id'], unique=False)
    op.create_table('graph_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='graphexecutionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('operation_count', sa.Integer(), nullable=False),
    sa.Column('failure_type', sa.String(length=255), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['graph_operation_batches.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_executions_batch_fingerprint'), 'graph_executions', ['batch_fingerprint'], unique=False)
    op.create_index(op.f('ix_graph_executions_batch_id'), 'graph_executions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_graph_executions_id'), 'graph_executions', ['id'], unique=False)
    op.create_index(op.f('ix_graph_executions_project_id'), 'graph_executions', ['project_id'], unique=False)
    op.create_table('review_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('proposed_claim_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='reviewstatus'), nullable=False),
    sa.Column('review_comment', sa.String(length=2000), nullable=True),
    sa.Column('reviewed_by', sa.String(length=150), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['proposed_claim_id'], ['proposed_claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_candidates_id'), 'review_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_review_candidates_project_id'), 'review_candidates', ['project_id'], unique=False)
    op.create_index(op.f('ix_review_candidates_proposed_claim_id'), 'review_candidates', ['proposed_claim_id'], unique=False)
    op.create_index(op.f('ix_review_candidates_status'), 'review_candidates', ['status'], unique=False)
    op.create_table('canonical_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.Enum('RELATIONSHIP', 'ATTRIBUTE', 'EXISTENCE', name='claimtype'), nullable=False),
    sa.Column('subject_entity_type', sa.String(length=80), nullable=False),
    sa.Column('subject_canonical_id', sa.String(length=255), nullable=False),
    sa.Column('predicate_value', sa.String(length=255), nullable=True),
    sa.Column('object_entity_type', sa.String(length=80), nullable=True),
    sa.Column('object_canonical_id', sa.String(length=255), nullable=True),
    sa.Column('object_value', sa.String(length=500), nullable=True),
    sa.Column('proposed_claim_id', sa.Integer(), nullable=False),
    sa.Column('review_candidate_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=150), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['proposed_claim_id'], ['proposed_claims.id'], ),
    sa.ForeignKeyConstraint(['review_candidate_id'], ['review_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_facts_id'), 'canonical_facts', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_facts_project_id'), 'canonical_facts', ['project_id'], unique=False)
    op.create_index(op.f('ix_canonical_facts_proposed_claim_id'), 'canonical_facts', ['proposed_claim_id'], unique=False)
    op.create_index(op.f('ix_canonical_facts_review_candidate_id'), 'canonical_facts', ['review_candidate_id'], unique=True)
    op.create_index(op.f('ix_canonical_facts_subject_canonical_id'), 'canonical_facts', ['subject_canonical_id'], unique=False)
    op.create_index(op.f('ix_canonical_facts_subject_entity_type'), 'canonical_facts', ['subject_entity_type'], unique=False)
    op.create_table('graph_execution_fingerprints',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['graph_executions.id'], ),
    sa.PrimaryKeyConstraint('fingerprint'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_table('graph_execution_operation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['graph_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_execution_operation_results_execution_id'), 'graph_execution_operation_results', ['execution_id'], unique=False)
    op.create_index(op.f('ix_graph_execution_operation_results_id'), 'graph_execution_operation_results', ['id'], unique=False)
    op.create_table('project_graph_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('canonical_id', sa.String(length=255), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_by_execution_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_execution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_execution_id'], ['graph_executions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by_execution_id'], ['graph_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'entity_type', 'canonical_id', name='uq_project_graph_node_natural_key')
    )
    op.create_index(op.f('ix_project_graph_nodes_id'), 'project_graph_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_project_graph_nodes_project_id'), 'project_graph_nodes', ['project_id'], unique=False)
    op.create_table('project_graph_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_entity_type', sa.String(length=80), nullable=False),
    sa.Column('source_canonical_id', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=255), nullable=False),
    sa.Column('target_entity_type', sa.String(length=80), nullable=False),
    sa.Column('target_canonical_id', sa.String(length=255), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_by_execution_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_execution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_execution_id'], ['graph_executions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['updated_by_execution_id'], ['graph_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_entity_type', 'source_canonical_id', 'relationship_type', 'target_entity_type', 'target_canonical_id', name='uq_project_graph_relationship_natural_key')
    )
    op.create_index(op.f('ix_project_graph_relationships_id'), 'project_graph_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_project_graph_relationships_project_id'), 'project_graph_relationships', ['project_id'], unique=False)
    op.create_table('proposed_claim_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposed_claim_id', sa.Integer(), nullable=False),
    sa.Column('engineering_index_entry_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('locator_kind', sa.Enum('PAGE', 'SHEET', 'CELL_RANGE', 'DRAWING_LAYOUT', 'REGION', 'OTHER', name='indexentrylocatorkind'), nullable=False),
    sa.Column('locator_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['engineering_index_entry_id'], ['engineering_index_entries.id'], ),
    sa.ForeignKeyConstraint(['proposed_claim_id'], ['proposed_claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposed_claim_id', 'engineering_index_entry_id', name='uq_evidence_reference_claim_and_entry')
    )
    op.create_index(op.f('ix_proposed_claim_evidence_document_id'), 'proposed_claim_evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_proposed_claim_evidence_engineering_index_entry_id'), 'proposed_claim_evidence', ['engineering_index_entry_id'], unique=False)
    op.create_index(op.f('ix_proposed_claim_evidence_id'), 'proposed_claim_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_proposed_claim_evidence_proposed_claim_id'), 'proposed_claim_evidence', ['proposed_claim_id'], unique=False)
    op.create_table('review_history_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_candidate_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='reviewstatus'), nullable=False),
    sa.Column('to_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_CHANGES', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=150), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['review_candidate_id'], ['review_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_history_events_id'), 'review_history_events', ['id'], unique=False)
    op.create_index(op.f('ix_review_history_events_review_candidate_id'), 'review_history_events', ['review_candidate_id'], unique=False)
    op.create_table('canonical_fact_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_fact_id', sa.Integer(), nullable=False),
    sa.Column('engineering_index_entry_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('locator_kind', sa.Enum('PAGE', 'SHEET', 'CELL_RANGE', 'DRAWING_LAYOUT', 'REGION', 'OTHER', name='indexentrylocatorkind'), nullable=False),
    sa.Column('locator_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['canonical_fact_id'], ['canonical_facts.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['engineering_index_entry_id'], ['engineering_index_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_fact_id', 'engineering_index_entry_id', name='uq_canonical_fact_evidence_fact_and_entry')
    )
    op.create_index(op.f('ix_canonical_fact_evidence_canonical_fact_id'), 'canonical_fact_evidence', ['canonical_fact_id'], unique=False)
    op.create_index(op.f('ix_canonical_fact_evidence_document_id'), 'canonical_fact_evidence', ['document_id'], unique=False)
    op.create_index(op.f('ix_canonical_fact_evidence_engineering_index_entry_id'), 'canonical_fact_evidence', ['engineering_index_entry_id'], unique=False)
    op.create_index(op.f('ix_canonical_fact_evidence_id'), 'canonical_fact_evidence', ['id'], unique=False)
    op.create_table('graph_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('source_fact_id', sa.Integer(), nullable=False),
    sa.Column('entity_project_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_canonical_id', sa.String(length=255), nullable=True),
    sa.Column('attribute', sa.String(length=255), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('subject_project_id', sa.Integer(), nullable=True),
    sa.Column('subject_entity_type', sa.String(length=80), nullable=True),
    sa.Column('subject_canonical_id', sa.String(length=255), nullable=True),
    sa.Column('relationship_type', sa.String(length=255), nullable=True),
    sa.Column('object_project_id', sa.Integer(), nullable=True),
    sa.Column('object_entity_type', sa.String(length=80), nullable=True),
    sa.Column('object_canonical_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['graph_operation_batches.id'], ),
    sa.ForeignKeyConstraint(['source_fact_id'], ['canonical_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_operations_batch_id'), 'graph_operations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_graph_operations_id'), 'graph_operations', ['id'], unique=False)
    op.create_index(op.f('ix_graph_operations_source_fact_id'), 'graph_operations', ['source_fact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_operations_source_fact_id'), table_name='graph_operations')
    op.drop_index(op.f('ix_graph_operations_id'), table_name='graph_operations')
    op.drop_index(op.f('ix_graph_operations_batch_id'), table_name='graph_operations')
    op.drop_table('graph_operations')
    op.drop_index(op.f('ix_canonical_fact_evidence_id'), table_name='canonical_fact_evidence')
    op.drop_index(op.f('ix_canonical_fact_evidence_engineering_index_entry_id'), table_name='canonical_fact_evidence')
    op.drop_index(op.f('ix_canonical_fact_evidence_document_id'), table_name='canonical_fact_evidence')
    op.drop_index(op.f('ix_canonical_fact_evidence_canonical_fact_id'), table_name='canonical_fact_evidence')
    op.drop_table('canonical_fact_evidence')
    op.drop_index(op.f('ix_review_history_events_review_candidate_id'), table_name='review_history_events')
    op.drop_index(op.f('ix_review_history_events_id'), table_name='review_history_events')
    op.drop_table('review_history_events')
    op.drop_index(op.f('ix_proposed_claim_evidence_proposed_claim_id'), table_name='proposed_claim_evidence')
    op.drop_index(op.f('ix_proposed_claim_evidence_id'), table_name='proposed_claim_evidence')
    op.drop_index(op.f('ix_proposed_claim_evidence_engineering_index_entry_id'), table_name='proposed_claim_evidence')
    op.drop_index(op.f('ix_proposed_claim_evidence_document_id'), table_name='proposed_claim_evidence')
    op.drop_table('proposed_claim_evidence')
    op.drop_index(op.f('ix_project_graph_relationships_project_id'), table_name='project_graph_relationships')
    op.drop_index(op.f('ix_project_graph_relationships_id'), table_name='project_graph_relationships')
    op.drop_table('project_graph_relationships')
    op.drop_index(op.f('ix_project_graph_nodes_project_id'), table_name='project_graph_nodes')
    op.drop_index(op.f('ix_project_graph_nodes_id'), table_name='project_graph_nodes')
    op.drop_table('project_graph_nodes')
    op.drop_index(op.f('ix_graph_execution_operation_results_id'), table_name='graph_execution_operation_results')
    op.drop_index(op.f('ix_graph_execution_operation_results_execution_id'), table_name='graph_execution_operation_results')
    op.drop_table('graph_execution_operation_results')
    op.drop_table('graph_execution_fingerprints')
    op.drop_index(op.f('ix_canonical_facts_subject_entity_type'), table_name='canonical_facts')
    op.drop_index(op.f('ix_canonical_facts_subject_canonical_id'), table_name='canonical_facts')
    op.drop_index(op.f('ix_canonical_facts_review_candidate_id'), table_name='canonical_facts')
    op.drop_index(op.f('ix_canonical_facts_proposed_claim_id'), table_name='canonical_facts')
    op.drop_index(op.f('ix_canonical_facts_project_id'), table_name='canonical_facts')
    op.drop_index(op.f('ix_canonical_facts_id'), table_name='canonical_facts')
    op.drop_table('canonical_facts')
    op.drop_index(op.f('ix_review_candidates_status'), table_name='review_candidates')
    op.drop_index(op.f('ix_review_candidates_proposed_claim_id'), table_name='review_candidates')
    op.drop_index(op.f('ix_review_candidates_project_id'), table_name='review_candidates')
    op.drop_index(op.f('ix_review_candidates_id'), table_name='review_candidates')
    op.drop_table('review_candidates')
    op.drop_index(op.f('ix_graph_executions_project_id'), table_name='graph_executions')
    op.drop_index(op.f('ix_graph_executions_id'), table_name='graph_executions')
    op.drop_index(op.f('ix_graph_executions_batch_id'), table_name='graph_executions')
    op.drop_index(op.f('ix_graph_executions_batch_fingerprint'), table_name='graph_executions')
    op.drop_table('graph_executions')
    op.drop_index(op.f('ix_entity_relations_target_entity_id'), table_name='entity_relations')
    op.drop_index(op.f('ix_entity_relations_source_entity_id'), table_name='entity_relations')
    op.drop_index(op.f('ix_entity_relations_project_id'), table_name='entity_relations')
    op.drop_index(op.f('ix_entity_relations_id'), table_name='entity_relations')
    op.drop_table('entity_relations')
    op.drop_index(op.f('ix_engineering_index_entries_project_id'), table_name='engineering_index_entries')
    op.drop_index(op.f('ix_engineering_index_entries_identifier'), table_name='engineering_index_entries')
    op.drop_index(op.f('ix_engineering_index_entries_id'), table_name='engineering_index_entries')
    op.drop_index(op.f('ix_engineering_index_entries_document_id'), table_name='engineering_index_entries')
    op.drop_table('engineering_index_entries')
    op.drop_index(op.f('ix_proposed_claims_subject'), table_name='proposed_claims')
    op.drop_index(op.f('ix_proposed_claims_project_id'), table_name='proposed_claims')
    op.drop_index(op.f('ix_proposed_claims_id'), table_name='proposed_claims')
    op.drop_table('proposed_claims')
    op.drop_index(op.f('ix_project_entities_project_id'), table_name='project_entities')
    op.drop_index(op.f('ix_project_entities_name'), table_name='project_entities')
    op.drop_index(op.f('ix_project_entities_id'), table_name='project_entities')
    op.drop_table('project_entities')
    op.drop_index(op.f('ix_graph_operation_batches_scope_id'), table_name='graph_operation_batches')
    op.drop_index(op.f('ix_graph_operation_batches_project_id'), table_name='graph_operation_batches')
    op.drop_index(op.f('ix_graph_operation_batches_id'), table_name='graph_operation_batches')
    op.drop_table('graph_operation_batches')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
