"""add canonical pdf representation

Milestone 26.1: the four tables holding the canonical textual
representation of a PDF - representation, page, block, span.

**Purely additive.** Four new tables and their indexes; no existing
table, column or constraint is touched. In particular nothing here
references or alters `documents.file_path`: the uploaded PDF stays
authoritative and untouched, and the representation is stored beside it
rather than over it.

The natural-key uniqueness constraint on (document_id, content_checksum,
representation_version) is the persistence-level idempotency backstop:
re-canonicalising unchanged bytes cannot produce a second row whatever
the caller does, while changed bytes carry a different checksum and are
therefore a new row alongside - never on top of - the old one.

Revision ID: b7ded1e07fcd
Revises: d5b93e17ca40
Create Date: 2026-07-28

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ded1e07fcd'
down_revision: Union[str, Sequence[str], None] = 'd5b93e17ca40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_pdf_representations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('content_checksum', sa.String(length=128), nullable=False),
    sa.Column('checksum_algorithm', sa.String(length=20), nullable=False),
    sa.Column('representation_version', sa.String(length=20), nullable=False),
    sa.Column('parser_name', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'content_checksum', 'representation_version', name='uq_canonical_pdf_document_checksum_version')
    )
    op.create_index(op.f('ix_canonical_pdf_representations_content_checksum'), 'canonical_pdf_representations', ['content_checksum'], unique=False)
    op.create_index('ix_canonical_pdf_representations_document_created', 'canonical_pdf_representations', ['document_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_canonical_pdf_representations_document_id'), 'canonical_pdf_representations', ['document_id'], unique=False)
    op.create_index(op.f('ix_canonical_pdf_representations_id'), 'canonical_pdf_representations', ['id'], unique=False)
    op.create_table('canonical_pdf_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('representation_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['representation_id'], ['canonical_pdf_representations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('representation_id', 'page_number', name='uq_canonical_pdf_page_number')
    )
    op.create_index(op.f('ix_canonical_pdf_pages_id'), 'canonical_pdf_pages', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_pdf_pages_representation_id'), 'canonical_pdf_pages', ['representation_id'], unique=False)
    op.create_table('canonical_pdf_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('TEXT', 'IMAGE', name='canonicalblockkind'), nullable=False),
    sa.Column('x0', sa.Float(), nullable=False),
    sa.Column('y0', sa.Float(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['canonical_pdf_pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'reading_order', name='uq_canonical_pdf_block_order')
    )
    op.create_index(op.f('ix_canonical_pdf_blocks_id'), 'canonical_pdf_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_pdf_blocks_page_id'), 'canonical_pdf_blocks', ['page_id'], unique=False)
    op.create_table('canonical_pdf_spans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('x0', sa.Float(), nullable=False),
    sa.Column('y0', sa.Float(), nullable=False),
    sa.Column('x1', sa.Float(), nullable=False),
    sa.Column('y1', sa.Float(), nullable=False),
    sa.Column('font_family', sa.String(length=150), nullable=False),
    sa.Column('font_size', sa.Float(), nullable=False),
    sa.Column('bold', sa.Boolean(), nullable=False),
    sa.Column('italic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['canonical_pdf_blocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'reading_order', name='uq_canonical_pdf_span_order')
    )
    op.create_index(op.f('ix_canonical_pdf_spans_block_id'), 'canonical_pdf_spans', ['block_id'], unique=False)
    op.create_index(op.f('ix_canonical_pdf_spans_id'), 'canonical_pdf_spans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canonical_pdf_spans_id'), table_name='canonical_pdf_spans')
    op.drop_index(op.f('ix_canonical_pdf_spans_block_id'), table_name='canonical_pdf_spans')
    op.drop_table('canonical_pdf_spans')
    op.drop_index(op.f('ix_canonical_pdf_blocks_page_id'), table_name='canonical_pdf_blocks')
    op.drop_index(op.f('ix_canonical_pdf_blocks_id'), table_name='canonical_pdf_blocks')
    op.drop_table('canonical_pdf_blocks')
    op.drop_index(op.f('ix_canonical_pdf_pages_representation_id'), table_name='canonical_pdf_pages')
    op.drop_index(op.f('ix_canonical_pdf_pages_id'), table_name='canonical_pdf_pages')
    op.drop_table('canonical_pdf_pages')
    op.drop_index(op.f('ix_canonical_pdf_representations_id'), table_name='canonical_pdf_representations')
    op.drop_index(op.f('ix_canonical_pdf_representations_document_id'), table_name='canonical_pdf_representations')
    op.drop_index('ix_canonical_pdf_representations_document_created', table_name='canonical_pdf_representations')
    op.drop_index(op.f('ix_canonical_pdf_representations_content_checksum'), table_name='canonical_pdf_representations')
    op.drop_table('canonical_pdf_representations')
    # ### end Alembic commands ###
